name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  run: 
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: Up memcached
        uses: niden/actions-memcached@v7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: latest
        id: v
      - name: Run linter
        run: v fmt -c .
      - name: Run tests
        run: v test .
